default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: C4c3c2c1
  locale: pt_BR.UTF8
  pool: 5
  #port diferente para usar na máquina local, sem ser no vagrant. Para usar no vagrant, comentar a linha abaixo
  port: 5433

development:
  <<: *default
  database: world_notes_development

test:
  <<: *default
  database: world_notes_test

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000